### ISSUE TITLE
关于数据源

### ISSUE THREAD

**Issue by chanchancl** [brainbush/api.matsuri.icu#1]
Hi,
我仔细看了你写的这份后端代码，API设计的很棒

我想问一下，API中的spider/ 接口，是由谁来调用的呢？

数据是用什么采集的。

谢谢

**Comment by brainbush** [comment]
spider的话，是我本地自己写的一个py程序采集的，用到了  xfgryujk/blivedm
目前没有公开代码的打算

**Comment by chanchancl** [comment]
多谢！
