### ISSUE TITLE
打扰了！想问下观看人数等问题

### ISSUE THREAD

**Issue by Yukio-s** [brainbush/api.matsuri.icu#2]
打扰惹！网站制作维护辛苦惹！顺带直播期间全部弹幕记录帮大忙了！真的非常感谢！
这里是对代码完全不懂的fw。。所以或许这个问题您有在别的地方写答案我也没有看懂十分抱歉。。

想请教下观看人数的记录原则，是只要观众点进直播间就算是观看嘛？还是有什么别的要求比如观看x分钟以上呢？

再就是导出全部弹幕功能，因为感觉方便做memo使用所以有在用，然而大多数记录官是用Excel开xml文件的【比如我】，载入xml文件时弹出指定的 XML 源不引用架构，什么都不懂的fw炒鸡迷惑所以就顺便也问一下。。希望没有给您添麻烦【鞠躬

再次感谢您的工具！【土下座

**Comment by brainbush** [comment]
观看人数的来源如下：
1. B站直播间里看到的（xxx进入了直播间、xxx关注了直播间、xxx分享了直播间）
2. 弹幕发言
3. 送礼物（金瓜子/银瓜子）
以上三个来源加起来按照B站uid去重获得的结果

至于导出XML的格式的话，是按照B站的主站视频的弹幕的XML形式导出的，主要是为了方便一些支持导入B站XML的播放器或者使用第三方的B站XML转字幕格式文件在播放器内看录播弹幕用的（至于直接看的话网页也行啊）
